// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFLV3Ap8qmAspEQ_8kqIyx4LH7V5PC9rU',
    appId: '1:502664654131:web:5afde7dbdca9f1fab3a246',
    messagingSenderId: '502664654131',
    projectId: 'logicodeapp-ba496',
    authDomain: 'logicodeapp-ba496.firebaseapp.com',
    storageBucket: 'logicodeapp-ba496.firebasestorage.app',
    measurementId: 'G-D3Q1P6F4J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'TU_API_KEY',
    appId: 'TU_APP_ID',
    messagingSenderId: 'TU_MESSAGING_SENDER_ID',
    projectId: 'logicodeapp-ba496',
    databaseURL: 'https://logicodeapp-ba496-default-rtdb.firebaseio.com', // 🔥 AGREGA ESTO
    storageBucket: 'logicodeapp-ba496.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsQFCp-82m4DvPdzRwLKyG0PDHyKTKoYs',
    appId: '1:502664654131:ios:6f6404a0e2d90e2cb3a246',
    messagingSenderId: '502664654131',
    projectId: 'logicodeapp-ba496',
    storageBucket: 'logicodeapp-ba496.firebasestorage.app',
    iosClientId: '502664654131-l32dbdjspj73m5t2vnv05glt1k6fv0tq.apps.googleusercontent.com',
    iosBundleId: 'com.example.logicode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsQFCp-82m4DvPdzRwLKyG0PDHyKTKoYs',
    appId: '1:502664654131:ios:6f6404a0e2d90e2cb3a246',
    messagingSenderId: '502664654131',
    projectId: 'logicodeapp-ba496',
    storageBucket: 'logicodeapp-ba496.firebasestorage.app',
    iosClientId: '502664654131-l32dbdjspj73m5t2vnv05glt1k6fv0tq.apps.googleusercontent.com',
    iosBundleId: 'com.example.logicode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFLV3Ap8qmAspEQ_8kqIyx4LH7V5PC9rU',
    appId: '1:502664654131:web:98dbb7ef5addd1b9b3a246',
    messagingSenderId: '502664654131',
    projectId: 'logicodeapp-ba496',
    authDomain: 'logicodeapp-ba496.firebaseapp.com',
    storageBucket: 'logicodeapp-ba496.firebasestorage.app',
    measurementId: 'G-WW03RPLTKS',
  );

}